org: arjones
app: aws-node-typescript-chrome-layer
service: aws-node-typescript-chrome-layer

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:31

functions:
  hello:
    handler: handler.hello
    timeout: 60

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    external:
      - '@sparticuz/chrome-aws-lambda'
      - 'puppeteer-core'